### ISSUE TITLE
Error with arpalazio adapter

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-fetch#393]
Running into following error occasionally with adapter, disabling for now.

```
2017-09-21T20:51:12.008Z - info: Running all fetch tasks.
/app/node_modules/cheerio/lib/parse.js:55
    var oldParent = node.parent || node.root,
                        ^

TypeError: Cannot read property 'parent' of undefined
    at Function.exports.update (/app/node_modules/cheerio/lib/parse.js:55:25)
    at module.exports (/app/node_modules/cheerio/lib/parse.js:17:11)
    at Function.exports.load (/app/node_modules/cheerio/lib/static.js:19:14)
    at Request._callback (/app/adapters/arpalazio.js:31:23)
    at self.callback (/app/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/app/node_modules/request/request.js:878:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketOnEnd (_http_client.js:344:9)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:934:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by dolugen** [comment]
Any idea why this is happening?

**Comment by jflasher** [comment]
Nope, looks to be something in cheerio, so I'm assuming it's some malformed item when trying to parse the data?

**Comment by dolugen** [comment]
Tried running the adapter locally today, and it works!

**Comment by jflasher** [comment]
Yeah, I think it will run sometimes and error sometimes? Probably points to unreliable source data.

**Comment by dolugen** [comment]
Hmm, should I review the adapter for ways to handle the input?

**Comment by jflasher** [comment]
So I think it's failing on the main `const $ = cheerio.load(body);` at line 31. I think there are probably two good things to add and maybe it can just be done in one go. Basically, we should check that input to make sure it's html to be parsed. The second is to try/catch the error so it doesn't crash the whole fetch routine if it fails. That can maybe just be done in 1 try/catch. If it's not valid html, don't know the adapter can do anything else but fail gracefully.
