### ISSUE TITLE
Fix envista adapter

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-fetch#603]
Uncaught error was causing fetch to crash. Should fix up the error, but also catch appropriately.

```
/app/adapters/envista.js:95
      const regionName = $('#lblCaption').text().split('-')[1].trim();
                                                              ^

TypeError: Cannot read property 'trim' of undefined
    at Request.request [as _callback] (/app/adapters/envista.js:75:26)
    at Request.self.callback (/app/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/app/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

**Comment by majesticio** [comment]
A new envista adapter has been written for the updated site and ready for PR once we have the API key.
