### ISSUE TITLE
Process hanging and not properly quitting on timeout

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-fetch#615]
We are seeing an issue where fetch will fail to connect to the database (which is not great obviously) but this causes the whole process to hang forever instead of being canceled at the 10 minute interval like we'd expect. Sample error log below.

@MichalCz we should probably just fail the whole task immediately if it fails to connect to the database, this should keep it from hanging. Where would be the best place to insert that in the streamy way?

```
Jun 18 21:01:06 openaq-fetch 9b25fa5d6ae9:  info Connecting to database. 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error Runtime error occurred in DataStream(14): Error: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at Promise.all.catch (/app/node_modules/scramjet/node_modules/scramjet-core/lib/util/mk-transform.js:59:44) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at <anonymous> 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at process._tickDomainCallback (internal/process/next_tick.js:229:7) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error       caused by: 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at /app/node_modules/knex/lib/client.js:339:13 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at /app/node_modules/bluebird/js/release/catch_filter.js:17:41 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:689:18) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at runCallback (timers.js:810:20) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at tryOnImmediate (timers.js:768:5) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at processImmediate [as _immediateCallback] (timers.js:745:5) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error       --- raised in DataStream(14) constructed --- 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at new PromiseTransformStream (/app/node_modules/scramjet/node_modules/scramjet-core/lib/util/promise-transform-stream.js:66:27) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at new DataStream (/app/node_modules/scramjet/node_modules/scramjet-core/lib/data-stream.js:68:9) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at DataStream.map (/app/node_modules/scramjet/node_modules/scramjet-core/lib/data-stream.js:187:26) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at streamMeasurementsToDBAndStorage (/app/lib/db.js:230:8) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at DataStream.use (/app/node_modules/scramjet/node_modules/scramjet-core/lib/data-stream.js:343:28) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at /app/fetch.js:66:8 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at Object.<anonymous> (/app/fetch.js:35:3) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at Module._compile (module.js:653:30) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at loader (/app/node_modules/babel-register/lib/node.js:144:5) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at Object.require.extensions.(anonymous function) [as .js] (/app/node_modules/babel-register/lib/node.js:154:7) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at Module.load (module.js:566:32) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at tryModuleLoad (module.js:506:12) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at Function.Module._load (module.js:498:3) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at Module.require (module.js:597:17) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at require (internal/module.js:11:18) 
Jun 18 21:01:52 openaq-fetch 9b25fa5d6ae9:  error         at Object.<anonymous> (/app/index.js:9:1) 
Jun 18 21:09:04 openaq-fetch 9b25fa5d6ae9:  error Still running sources at time out: EEA Andorra,StateAir_AbuDhabi,StateAir_Dubai,Australia - New South Wales,Australia - 
```

**Comment by MichalCz** [comment]
Hi @jflasher.

I need to take a look at this - I just noticed the issue.

**Comment by jflasher** [comment]
Thanks! I think we’re doing better lately but would be good to get this handled in case it comes up again.

**Comment by MichalCz** [comment]
@jflasher so I think we can fail the task immediately (i.e. not wait for completion), but the method has also s3 storage - so I gather that should be completed regardless of the DB failure?

**Comment by MichalCz** [comment]
Joe, we already do a fail-fast is the db connection cannot be obtained. I suspect that one of the `cleanups` is making the process hang. Do you happen to have a little more logs - like `debug` level from here: 

[lib/errors.js:262](https://github.com/openaq/openaq-fetch/blob/develop/lib/errors.js#L262)

```
    try {
      log.debug(`Executing cleanup ${operation._name}`);
      await operation();
      log.debug(`Cleanup ${operation._name} completed`);
    } catch (e) {
      log.warn(`Exception "${e.message}" occured during cleanup "${operation._name}"`);
    }
```

**Comment by MichalCz** [comment]
@jflasher I'm getting:

```
2019-08-23T20:52:37.666Z - error: Runtime error occurred in DataStream(9): Error: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at promise.catch (/workspaces/scramjet-dev-container/openaq-fetch/node_modules/scramjet/node_modules/scramjet-core/lib/util/promise-transform-stream.js:229:31)
  caused by:
```

And a process exit with 199 exit status. Could this be something else than a database?

**Comment by majesticio** [comment]
Fetch process has been updated and issue is stale. Closing until new information comes to light.
